[config]

[templates.hyprland-colors]
input_path = "~/.config/matugen/templates/hyprland-colors.conf"
output_path = "~/.config/hypr/colors.conf"
post_hook = "hyprctl reload"

[templates.dunstrc]
input_path = "~/.config/matugen/templates/dunstrc"
output_path = "~/.config/dunst/dunstrc"
post_hook = "killall dunst 2>/dev/null; dunst &"
