$primary = rgb(cdbdff)
$on_primary = rgb(34275e)
$primary_container = rgb(4b3e76)
$on_primary_container = rgb(e8deff)
$secondary = rgb(cbc3dc)
$secondary_container = rgb(494458)
$on_secondary_container = rgb(e7def8)
$tertiary = rgb(eeb8ca)
$tertiary_container = rgb(633b4a)
$surface = rgb(141318)
$surface_dim = rgb(141318)
$surface_container = rgb(201f24)
$surface_container_low = rgb(1c1b20)
$surface_container_high = rgb(2b292f)
$on_surface = rgb(e6e1e9)
$on_surface_variant = rgb(cac4cf)
$outline = rgb(938f99)
$error = rgb(ffb4ab)
