$primary = rgb(aec6ff)
$on_primary = rgb(112f60)
$primary_container = rgb(2c4678)
$on_primary_container = rgb(d8e2ff)
$secondary = rgb(bfc6dc)
$secondary_container = rgb(3f4759)
$on_secondary_container = rgb(dbe2f9)
$tertiary = rgb(debcdf)
$tertiary_container = rgb(583e5a)
$surface = rgb(111318)
$surface_dim = rgb(111318)
$surface_container = rgb(1e1f25)
$surface_container_low = rgb(1a1b20)
$surface_container_high = rgb(282a2f)
$on_surface = rgb(e2e2e9)
$on_surface_variant = rgb(c5c6d0)
$outline = rgb(8e9099)
$error = rgb(ffb4ab)
