font_size 13.0
window_padding_width 8
font_family      JetBrainsMono Nerd Font
italic_font      auto
# bold_font        auto
bold_italic_font auto
include theme.conf

# Cursor styling
cursor #f5c2e7
cursor_text_color #1e1e2e
cursor_shape beam
cursor_shape_unfocused hollow
cursor_beam_thickness 2.4
cursor_blink_interval 0.65 ease-in-out
cursor_stop_blinking_after 12.0
cursor_trail 25
cursor_trail_decay 0.08 0.28
cursor_trail_start_threshold 2
cursor_trail_color #cba6f7

# Hyperlinks
allow_hyperlinks yes
detect_urls yes
underline_hyperlinks hover
url_style straight
url_color #89b4fa
show_hyperlink_targets ctrl

#background_opacity 0.60
#hide_window_decorations yes
#confirm_os_window_close 0

select_by_word_characters @-./_~?&=%+#*$!
paste_actions quote-urls-at-prompt

confirm_os_window_close 0
