# Matugen generated kitty theme

# Basic colors
foreground              #e2e2e9
background              #111318
selection_foreground    #0f2f60
selection_background    #adc7ff

# Cursor colors
cursor                  #adc7ff
cursor_text_color       #0f2f60

# URL underline color when hovering with mouse
url_color               #debcdf

# Kitty window border colors
active_border_color     #adc7ff
inactive_border_color   #8e9099
bell_border_color       #ffb4ab

# OS Window titlebar colors
wayland_titlebar_color system
macos_titlebar_color system

# Tab bar colors
active_tab_foreground   #0f2f60
active_tab_background   #adc7ff
inactive_tab_foreground #c4c6d0
inactive_tab_background #1e2025
tab_bar_background      #111318

# Colors for marks
mark1_foreground #0f2f60
mark1_background #adc7ff
mark2_foreground #283041
mark2_background #bfc6dc
mark3_foreground #402843
mark3_background #debcdf

# The 16 terminal colors

# black
color0 #111318
color8 #282a2f

# red
color1 #ffb4ab
color9 #ffb4ab

# green
color2  #debcdf
color10 #debcdf

# yellow
color3  #583e5b
color11 #583e5b

# blue
color4  #adc7ff
color12 #adc7ff

# magenta
color5  #bfc6dc
color13 #bfc6dc

# cyan
color6  #debcdf
color14 #debcdf

# white
color7  #e2e2e9
color15 #c4c6d0
